language: go
go:
- master
install:
  - go get -t -d -v ./...
  - go get github.com/mitchellh/gox
sudo: required
before_deploy:
  - gox -osarch="linux/arm linux/386 linux/amd64 windows/386 windows/amd64 darwin/386 darwin/amd64" -ldflags "-X main.AppVersion=$TRAVIS_TAG -X main.Sha=$TRAVIS_COMMIT" -output "dist/dynroute53-{{.OS}}-{{.Arch}}"
  - sudo chmod +x ./dist/*
deploy:
  provider: releases
  api_key:
    secure: I/B7ZtB8ADjuc8LCqCk2/YR5KAC4WieW6tnz5SkghoWCOPiVpmosRXS8MH1BnTCTzK388REPGZ43ZjUsnNc/Hi6VbigWOzG/JmR8B/tj8dslCLtwcS1ICLT3I+jdwAyi/XWv5BBauDUuE3rQX2wDrqs4AZ0FXsYnZ+sXo9gOyCBzkFR1/ut8sb0LuZoD6tLjv7I1ZrrhvPUdWYGSl/KTlibm/vzWQE0UuamQTK0BCkaqfhLMkUeFODTKwUUMnHvWoKBcuAxywifaavHP6NfqgeBq6V8aXhB7TRSEFi0zAtsuKshObNPwE/6u0bgW2sdY3ICB5MmkxYBP5V5Ma1sZNECzoBKD5IS7Fbig6lyYu4hwuNhDQSIIptk4Nmb2hj41PxxhF14Zg48UvrjUm/4dWcy6rrux0D0RJEqLRQQtfEQKoypFx+adZwd5mngyvDLc16h/d4yBZSiUlamEKZTpwMOMs0EerTP/2Xu9NMxJg5usLVxinyzZCOEzl6tp3sUKnwUz9ixpKA5B3crgVqPEih+JvhRNjJ9R4jTVY60Sw23BuikEEtlJ2DnzbJzK6H6Nn5d87YHdiOR3AJQeWi1wBofr5eqLUr8uYrDP4KaLNqGsSmUFu7YZdcExQqS8fF7gc9qXHA7mYDOjQ2zQNIy7eXNo/EGFfMMfjTKlPQCm1Bw=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: thoeni/dynroute53
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9]+(.[0-9]+)*"